_wandb:
    value:
        cli_version: 0.18.6
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "1": epoch/learning_rate
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.0
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 5
                - 53
                - 55
            "3":
                - 7
                - 13
                - 23
                - 38
                - 55
            "4": 3.10.0
            "5": 0.18.6
            "8":
                - 3
                - 5
            "12": 0.18.6
            "13": windows-amd64
